name: Publish

on:
  push: 
    branches: [ main ]

defaults:
  run:
    working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release /p:Version=1.0.${{github.run_number}}
    - name: Test
      run: dotnet test --no-build -c Release SimpleRecurringJobs.Tests
    - name: Pack
      run: dotnet pack --no-build -c Release -o packages /p:Version=1.0.${{github.run_number}}  
    - name: Push
      run: dotnet nuget push packages/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_KEY}}

